(() => {
  'use strict';

  const PORTFOLIO = Object.freeze({
    name: 'Rana Hamza', role: 'UI/UX Architect & Developer', location: 'Faisalabad, Pakistan',
    about: 'I build polished, human-centered web experiences at the intersection of design and engineering.',
    skills: ['UI/UX design', 'React', 'Next.js', 'TypeScript', 'Progressive Web Apps'],
    projects: ['ArshUX Terminal — an offline-first terminal experience', 'Product interfaces — accessible, responsive web applications'],
    contact: 'Open an issue in this repository to get in touch.', resume: 'Resume available on request.', socials: ['GitHub: github.com/ranag786tech-lang']
  });
  const THEMES = ['matrix', 'cyberpunk', 'dracula', 'ubuntu', 'hacker', 'windows95', 'nord'];
  const COMMANDS = ['about','alias','cat','cd','clear','coffee','contact','echo','fortune','help','ls','matrix','mkdir','projects','pwd','python3','resume','rm','skills','socials','sudo','theme','touch','tree','whoami','write'];
  const DB_NAME = 'ArshUX_Omni_DB'; const STORE = 'terminal-state'; const STATE_KEY = 'state';

  class Storage {
    async open() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 2); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
    async load() { const db = await this.open(); return new Promise((resolve, reject) => { const request = db.transaction(STORE, 'readonly').objectStore(STORE).get(STATE_KEY); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
    async save(value) { const db = await this.open(); return new Promise((resolve, reject) => { const tx = db.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(value, STATE_KEY); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
  }

  class VirtualFileSystem {
    constructor(snapshot) { this.dirs = new Set(snapshot?.dirs || ['/', '/home', '/home/arsh']); this.files = new Map(snapshot?.files || []); }
    snapshot() { return { dirs: [...this.dirs], files: [...this.files] }; }
    resolve(input = '.', cwd = '/home/arsh') { const raw = input === '~' || input.startsWith('~/') ? `/home/arsh${input.slice(1)}` : input.startsWith('/') ? input : `${cwd}/${input}`; const parts = []; raw.split('/').forEach(part => { if (!part || part === '.') return; if (part === '..') parts.pop(); else parts.push(part); }); return `/${parts.join('/')}` || '/'; }
    exists(path) { return this.dirs.has(path) || this.files.has(path); }
    isDir(path) { return this.dirs.has(path); }
    parent(path) { return path === '/' ? '/' : path.slice(0, path.lastIndexOf('/')) || '/'; }
    list(path) { if (!this.isDir(path)) throw new Error(`ls: cannot access '${path}': No such directory`); const prefix = path === '/' ? '/' : `${path}/`; return [...new Set([...this.dirs, ...this.files.keys()].filter(item => item !== path && item.startsWith(prefix)).map(item => item.slice(prefix.length).split('/')[0]))].sort(); }
    mkdir(path) { if (this.exists(path)) throw new Error(`mkdir: cannot create directory '${path}': File exists`); if (!this.isDir(this.parent(path))) throw new Error(`mkdir: cannot create directory '${path}': No such parent directory`); this.dirs.add(path); }
    touch(path) { if (this.isDir(path)) throw new Error(`touch: cannot touch '${path}': Is a directory`); if (!this.isDir(this.parent(path))) throw new Error(`touch: cannot touch '${path}': No such parent directory`); if (!this.files.has(path)) this.files.set(path, ''); }
    read(path) { if (!this.files.has(path)) throw new Error(`cat: ${path}: No such file`); return this.files.get(path); }
    write(path, content) { if (!this.isDir(this.parent(path))) throw new Error(`write: ${path}: No such parent directory`); if (this.isDir(path)) throw new Error(`write: ${path}: Is a directory`); this.files.set(path, content); }
    remove(path, recursive) { if (this.files.delete(path)) return; if (!this.isDir(path)) throw new Error(`rm: cannot remove '${path}': No such file or directory`); const children = [...this.dirs, ...this.files.keys()].filter(item => item.startsWith(`${path}/`)); if (children.length && !recursive) throw new Error(`rm: cannot remove '${path}': Is a directory`); if (!recursive) throw new Error(`rm: cannot remove '${path}': Is a directory`); children.filter(item => this.files.has(item)).forEach(item => this.files.delete(item)); children.filter(item => this.dirs.has(item)).sort((a,b) => b.length - a.length).forEach(item => this.dirs.delete(item)); this.dirs.delete(path); }
    tree(path, indent = '') { const result = []; this.list(path).forEach((name, index, names) => { const child = this.resolve(name, path); const branch = index === names.length - 1 ? '└── ' : '├── '; result.push(`${indent}${branch}${name}${this.isDir(child) ? '/' : ''}`); if (this.isDir(child)) result.push(...this.tree(child, `${indent}${index === names.length - 1 ? '    ' : '│   '}`)); }); return result; }
  }

  const tokenize = input => input.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)?.map(part => part.replace(/^['"]|['"]$/g, '')) || [];
  const distance = (a, b) => { const rows = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 0; i < a.length; i++) { let previous = rows[0]++; for (let j = 0; j < b.length; j++) { const current = rows[j + 1]; rows[j + 1] = Math.min(rows[j + 1] + 1, rows[j] + 1, previous + (a[i] === b[j] ? 0 : 1)); previous = current; } } return rows[b.length]; };

  class Terminal {
    constructor() { this.storage = new Storage(); this.fs = new VirtualFileSystem(); this.tabs = []; this.active = null; this.aliases = { ll: 'ls' }; this.theme = ''; this.py = null; this.elements = { tabs: document.querySelector('#tabs'), terminals: document.querySelector('#terminals'), input: document.querySelector('#cmdIn'), prompt: document.querySelector('#currentDir'), suggestions: document.querySelector('#suggestions') }; }
    async boot() { try { const state = await this.storage.load(); if (state) { this.fs = new VirtualFileSystem(state.fs); this.aliases = { ...this.aliases, ...state.aliases }; this.applyTheme(state.theme || ''); } } catch { /* IndexedDB may be unavailable in private browsing. */ } this.newTab('main'); if (new URLSearchParams(location.search).get('action') === 'new_tab') this.newTab(); this.print('ArshUX OMNI Kernel v2.0 ready.', 'sys'); this.print("Type 'help' to explore commands. Press Tab to autocomplete.", 'warn'); }
    async persist() { try { await this.storage.save({ fs: this.fs.snapshot(), aliases: this.aliases, theme: this.theme }); } catch { this.print('Storage unavailable: changes will only last for this session.', 'warn'); } }
    newTab(name = 'bash') { const id = `T${Date.now()}_${this.tabs.length}`; const tab = { id, name, cwd: '/home/arsh', history: [], hIdx: -1 }; this.tabs.push(tab); const button = document.createElement('button'); button.type = 'button'; button.className = 'tab'; button.id = `btn${id}`; button.textContent = name; button.addEventListener('click', () => this.switch(id)); this.elements.tabs.append(button); const pane = document.createElement('section'); pane.className = 'pane'; pane.id = id; pane.setAttribute('aria-label', `${name} terminal output`); this.elements.terminals.append(pane); this.switch(id); button.scrollIntoView({ block: 'nearest', inline: 'nearest' }); }
    switch(id) { this.tabs.forEach(tab => { document.getElementById(tab.id).classList.remove('active'); document.getElementById(`btn${tab.id}`).classList.remove('active'); }); this.active = this.tabs.find(tab => tab.id === id); document.getElementById(id).classList.add('active'); document.getElementById(`btn${id}`).classList.add('active'); this.updatePrompt(); this.elements.input.focus({ preventScroll: true }); }
    updatePrompt() { this.elements.prompt.textContent = `${this.active.cwd.replace('/home/arsh', '~')} ❯`; }
    print(message = '', kind = '') { const line = document.createElement('div'); line.className = `ln ${kind}`; line.textContent = message; const pane = document.getElementById(this.active.id); pane.append(line); pane.scrollTop = pane.scrollHeight; }
    clear() { document.getElementById(this.active.id).replaceChildren(); }
    async execute(raw) { const input = raw.trim(); if (!input) return; const tab = this.active; if (tab.history[0] !== input) tab.history.unshift(input); tab.hIdx = -1; this.print(`${this.elements.prompt.textContent} ${input}`, 'muted'); let [command, ...args] = tokenize(input); command = this.aliases[command] || command; try { await this.run(command, args); } catch (error) { this.print(error.message || 'Command failed.', 'err'); } }
    async run(command, args) { const path = value => this.fs.resolve(value, this.active.cwd); const onePath = (label, values) => { if (!values[0]) throw new Error(`Usage: ${label} <path>`); return path(values[0]); };
      if (command === 'help') { this.print('Filesystem: ls, cd, pwd, mkdir, touch, cat, write, rm, tree'); this.print('Terminal: clear, alias, theme, help, echo, python3 | Portfolio: about, skills, projects, contact, resume, socials'); this.print('Fun: coffee, fortune, matrix, whoami, hack nasa, sudo make me a sandwich'); return; }
      if (command === 'pwd') return this.print(this.active.cwd); if (command === 'clear') return this.clear();
      if (command === 'echo') return this.print(args.join(' '));
      if (command === 'ls') { const target = path(args[0] || '.'); return this.print(this.fs.list(target).map(name => this.fs.isDir(this.fs.resolve(name, target)) ? `${name}/` : name).join('  ') || 'Directory empty.', 'ok'); }
      if (command === 'cd') { const target = path(args[0] || '~'); if (!this.fs.isDir(target)) throw new Error(`cd: ${args[0] || '~'}: No such directory`); this.active.cwd = target; return this.updatePrompt(); }
      if (command === 'mkdir') { const target = onePath('mkdir', args); this.fs.mkdir(target); await this.persist(); return this.print(`created directory '${args[0]}'`, 'ok'); }
      if (command === 'touch') { const target = onePath('touch', args); this.fs.touch(target); await this.persist(); return; }
      if (command === 'cat') return this.print(this.fs.read(onePath('cat', args)));
      if (command === 'write') { if (args.length < 2) throw new Error('Usage: write <file> <content>'); this.fs.write(path(args[0]), args.slice(1).join(' ')); await this.persist(); return this.print(`saved '${args[0]}'`, 'ok'); }
      if (command === 'rm') { const recursive = args[0] === '-r' || args[0] === '-rf'; const target = onePath('rm', recursive ? args.slice(1) : args); this.fs.remove(target, recursive); if (this.active.cwd === target || this.active.cwd.startsWith(`${target}/`)) { this.active.cwd = '/home/arsh'; this.updatePrompt(); } await this.persist(); return; }
      if (command === 'tree') { const target = path(args[0] || '.'); if (!this.fs.isDir(target)) throw new Error(`tree: ${args[0]}: Not a directory`); this.print(`${target}/\n${this.fs.tree(target).join('\n') || '└── (empty)'}`, 'ok'); return; }
      if (command === 'alias') { if (!args.length) return this.print(Object.entries(this.aliases).map(([key, value]) => `${key}='${value}'`).join('\n')); const [key, value] = args.join(' ').split('='); if (!key || !value || !/^[\w-]+$/.test(key)) throw new Error('Usage: alias name=command'); this.aliases[key] = value.trim(); await this.persist(); return this.print(`alias ${key}='${this.aliases[key]}'`, 'ok'); }
      if (command === 'theme') { if (!args.length) return this.print(`Current: ${this.theme || 'default'}\nAvailable: default, ${THEMES.join(', ')}`); const selected = args[0] === 'default' ? '' : args[0]; if (selected && !THEMES.includes(selected)) throw new Error(`theme: '${args[0]}' is not available`); this.applyTheme(selected); await this.persist(); return this.print(`Theme switched to ${selected || 'default'}.`, 'ok'); }
      if (command === 'python3') { const code = args.join(' ') || "print('Python Omni Active')"; if (!this.py) { this.print('Loading Python engine…', 'sys'); await this.loadPython(); } const result = await this.py.runPythonAsync(code); if (result !== undefined) this.print(String(result), 'ok'); return; }
      if (Object.hasOwn(PORTFOLIO, command)) return this.print(Array.isArray(PORTFOLIO[command]) ? PORTFOLIO[command].map((item, index) => `${index + 1}. ${item}`).join('\n') : PORTFOLIO[command]);
      if (command === 'whoami') return this.print(`${PORTFOLIO.name} | ${PORTFOLIO.role}`, 'ok'); if (command === 'coffee') return this.print('☕ Brewing focus... done. Ship something thoughtful.', 'warn'); if (command === 'fortune') return this.print('“The best interface is the one that lets people finish their work.”'); if (command === 'matrix') return Array.from({ length: 8 }, () => this.print(Math.random().toString(2).slice(2, 42), 'ok'));
      if (command === 'hack' && args.join(' ') === 'nasa') return this.print('Nice try, commander. This terminal only launches good ideas.', 'warn'); if (command === 'sudo' && args.join(' ') === 'make me a sandwich') return this.print('Okay. 🥪', 'ok');
      const suggestion = COMMANDS.sort((a,b) => distance(command, a) - distance(command, b))[0]; throw new Error(`Omni: command '${command}' not found.${suggestion && distance(command, suggestion) <= 3 ? ` Did you mean '${suggestion}'?` : " Type 'help' for commands."}`);
    }
    applyTheme(theme) { this.theme = theme; document.documentElement.dataset.theme = theme; document.querySelector('meta[name="theme-color"]').content = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(); }
    async loadPython() { if (window.loadPyodide) { this.py = await window.loadPyodide(); return; } await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.js'; script.async = true; script.onload = resolve; script.onerror = () => reject(new Error('Python engine could not load. Connect to the internet and try again.')); document.head.append(script); }); this.py = await window.loadPyodide(); }
    complete() { const value = this.elements.input.value; const tokens = tokenize(value); if (value.endsWith(' ')) return; const candidate = tokens.length <= 1 ? COMMANDS.concat(Object.keys(this.aliases)) : this.fs.list(this.active.cwd); const needle = tokens.at(-1) || ''; const matches = candidate.filter(item => item.startsWith(needle)); if (matches.length === 1) { const suffix = matches[0].slice(needle.length); this.insert(suffix); this.elements.suggestions.textContent = ''; } else { this.elements.suggestions.textContent = matches.length ? `Suggestions: ${matches.join('  ')}` : 'No matching command or file.'; } }
    insert(text) { const input = this.elements.input; input.setRangeText(text, input.selectionStart ?? input.value.length, input.selectionEnd ?? input.value.length, 'end'); input.focus({ preventScroll: true }); }
    history(direction) { const tab = this.active; if (direction < 0 && tab.history.length > tab.hIdx + 1) tab.hIdx++; else if (direction > 0 && tab.hIdx >= 0) tab.hIdx--; this.elements.input.value = tab.hIdx >= 0 ? tab.history[tab.hIdx] : ''; }
  }

  const terminal = new Terminal();
  document.querySelector('#newTab').addEventListener('click', () => terminal.newTab());
  document.querySelector('#keybar').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.insert) terminal.insert(button.dataset.insert); const key = button.dataset.key; if (key === 'ArrowUp') terminal.history(-1); if (key === 'ArrowDown') terminal.history(1); if (key === 'Tab') terminal.complete(); if (key === 'Escape') terminal.elements.input.value = ''; if (key === 'CtrlC') { terminal.elements.input.value = ''; terminal.print('^C', 'err'); } terminal.elements.input.focus({ preventScroll: true }); });
  terminal.elements.input.addEventListener('keydown', async event => { if (event.key === 'Enter') { event.preventDefault(); const value = event.target.value; event.target.value = ''; terminal.elements.suggestions.textContent = ''; await terminal.execute(value); } else if (event.key === 'ArrowUp') { event.preventDefault(); terminal.history(-1); } else if (event.key === 'ArrowDown') { event.preventDefault(); terminal.history(1); } else if (event.key === 'Tab') { event.preventDefault(); terminal.complete(); } else if (event.key === 'Escape') { terminal.elements.input.value = ''; terminal.elements.suggestions.textContent = ''; } else if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); terminal.clear(); } });
  terminal.elements.input.addEventListener('input', () => { terminal.elements.suggestions.textContent = ''; });
  terminal.elements.input.addEventListener('focus', () => requestAnimationFrame(() => { const pane = document.getElementById(terminal.active?.id); if (pane) pane.scrollTop = pane.scrollHeight; }));
  if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('sw.js', { scope: './' }).catch(error => console.warn('Service worker registration failed:', error)));
  terminal.boot();
})();
