(() => {
  'use strict';

  const APP = 'Arshux Omni';
  const HOME = '/home/arsh';
  const DB_NAME = 'Arshux_Omni_DB'; const STORE = 'terminal-state'; const STATE_KEY = 'state';
  const THEMES = ['matrix', 'cyberpunk', 'dracula', 'ubuntu', 'hacker', 'windows95', 'nord'];
  const PACKAGES = { git: '2.45.2 (browser workspace tools)', python: '3.12 (Pyodide runtime)', ripgrep: '14.1.0 (planned WASM)', node: '22 (backend required)' };
  const PORTFOLIO = Object.freeze({ name: 'Rana Hamza', role: 'UI/UX Architect & Developer', location: 'Faisalabad, Pakistan', about: 'I build polished, human-centered web experiences at the intersection of design and engineering.', skills: ['UI/UX design', 'React', 'Next.js', 'TypeScript', 'Progressive Web Apps'], projects: ['ArshUX Terminal — an offline-first terminal experience', 'Product interfaces — accessible, responsive web applications'], contact: 'Open an issue in this repository to get in touch.', resume: 'Resume available on request.', socials: ['GitHub: github.com/ranag786tech-lang'] });

  class Storage {
    async open() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 3); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(STORE)) request.result.createObjectStore(STORE); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
    async load() { const db = await this.open(); return new Promise((resolve, reject) => { const request = db.transaction(STORE, 'readonly').objectStore(STORE).get(STATE_KEY); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
    async save(value) { const db = await this.open(); return new Promise((resolve, reject) => { const tx = db.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(value, STATE_KEY); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
  }

  class VirtualFileSystem {
    constructor(snapshot) { this.dirs = new Set(snapshot?.dirs || ['/', '/home', HOME]); this.files = new Map(snapshot?.files || []); }
    snapshot() { return { dirs: [...this.dirs], files: [...this.files] }; }
    resolve(input = '.', cwd = HOME) { const raw = input === '~' || input.startsWith('~/') ? `${HOME}${input.slice(1)}` : input.startsWith('/') ? input : `${cwd}/${input}`; const parts = []; raw.split('/').forEach(part => { if (!part || part === '.') return; if (part === '..') parts.pop(); else parts.push(part); }); return `/${parts.join('/')}` || '/'; }
    parent(path) { return path === '/' ? '/' : path.slice(0, path.lastIndexOf('/')) || '/'; }
    exists(path) { return this.dirs.has(path) || this.files.has(path); } isDir(path) { return this.dirs.has(path); }
    list(path) { if (!this.isDir(path)) throw new Error(`ls: cannot access '${path}': No such directory`); const prefix = path === '/' ? '/' : `${path}/`; return [...new Set([...this.dirs, ...this.files.keys()].filter(item => item !== path && item.startsWith(prefix)).map(item => item.slice(prefix.length).split('/')[0]))].sort(); }
    mkdir(path, parents = false) { if (this.exists(path)) { if (parents && this.isDir(path)) return; throw new Error(`mkdir: cannot create directory '${path}': File exists`); } if (parents) { const parts = path.split('/').filter(Boolean); let current = ''; for (const part of parts) { current += `/${part}`; if (this.files.has(current)) throw new Error(`mkdir: cannot create directory '${path}': File exists`); this.dirs.add(current); } return; } if (!this.isDir(this.parent(path))) throw new Error(`mkdir: cannot create directory '${path}': No such parent directory`); this.dirs.add(path); }
    touch(path) { if (this.isDir(path)) throw new Error(`touch: cannot touch '${path}': Is a directory`); if (!this.isDir(this.parent(path))) throw new Error(`touch: cannot touch '${path}': No such parent directory`); if (!this.files.has(path)) this.files.set(path, ''); }
    read(path) { if (this.isDir(path)) throw new Error(`cat: ${path}: Is a directory`); if (!this.files.has(path)) throw new Error(`cat: ${path}: No such file`); return this.files.get(path); }
    write(path, content) { if (!this.isDir(this.parent(path))) throw new Error(`write: ${path}: No such parent directory`); if (this.isDir(path)) throw new Error(`write: ${path}: Is a directory`); this.files.set(path, content); }
    remove(path, recursive) { if (path === '/' || path === HOME) throw new Error('rm: refusing to remove protected workspace directory'); if (this.files.delete(path)) return; if (!this.isDir(path)) throw new Error(`rm: cannot remove '${path}': No such file or directory`); const children = [...this.dirs, ...this.files.keys()].filter(item => item.startsWith(`${path}/`)); if (!recursive) throw new Error(`rm: cannot remove '${path}': Is a directory`); children.filter(item => this.files.has(item)).forEach(item => this.files.delete(item)); children.filter(item => this.dirs.has(item)).sort((a, b) => b.length - a.length).forEach(item => this.dirs.delete(item)); this.dirs.delete(path); }
    copy(source, destination) { if (!this.exists(source)) throw new Error(`cp: cannot stat '${source}': No such file or directory`); if (this.isDir(source)) throw new Error('cp: directory copy requires -r'); if (this.isDir(destination)) destination = this.resolve(source.slice(source.lastIndexOf('/') + 1), destination); if (!this.isDir(this.parent(destination))) throw new Error(`cp: cannot create '${destination}': No such parent directory`); this.files.set(destination, this.read(source)); return destination; }
    move(source, destination) { if (!this.exists(source)) throw new Error(`mv: cannot stat '${source}': No such file or directory`); if (this.isDir(destination)) destination = this.resolve(source.slice(source.lastIndexOf('/') + 1), destination); if (!this.isDir(this.parent(destination))) throw new Error(`mv: cannot move to '${destination}': No such parent directory`); if (this.isDir(source)) { if (destination.startsWith(`${source}/`)) throw new Error('mv: cannot move a directory into itself'); const entries = [...this.dirs, ...this.files.keys()].filter(item => item === source || item.startsWith(`${source}/`)).sort((a,b) => a.length-b.length); for (const entry of entries) { const next = destination + entry.slice(source.length); if (this.dirs.has(entry)) { this.dirs.add(next); this.dirs.delete(entry); } else { this.files.set(next, this.files.get(entry)); this.files.delete(entry); } } } else { this.files.set(destination, this.files.get(source)); this.files.delete(source); } return destination; }
    tree(path, indent = '') { const names = this.list(path); return names.flatMap((name, index) => { const child = this.resolve(name, path); const last = index === names.length - 1; const branch = `${indent}${last ? '└── ' : '├── '}${name}${this.isDir(child) ? '/' : ''}`; return this.isDir(child) ? [branch, ...this.tree(child, `${indent}${last ? '    ' : '│   '}`)] : [branch]; }); }
  }

  const tokenize = input => input.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)?.map(part => part.replace(/^['"]|['"]$/g, '')) || [];
  const distance = (a, b) => { const rows = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 0; i < a.length; i++) { let previous = rows[0]++; for (let j = 0; j < b.length; j++) { const current = rows[j + 1]; rows[j + 1] = Math.min(rows[j + 1] + 1, rows[j] + 1, previous + (a[i] === b[j] ? 0 : 1)); previous = current; } } return rows[b.length]; };

  class Terminal {
    constructor() { this.storage = new Storage(); this.fs = new VirtualFileSystem(); this.tabs = []; this.active = null; this.aliases = { ll: 'ls' }; this.theme = ''; this.py = null; this.packages = new Set(); this.gitRepos = {}; this.aiEndpoint = ''; this.elements = { tabs: document.querySelector('#tabs'), terminals: document.querySelector('#terminals'), input: document.querySelector('#cmdIn'), prompt: document.querySelector('#currentDir'), suggestions: document.querySelector('#suggestions'), editor: document.querySelector('#editor'), editorPath: document.querySelector('#editorPath'), editorText: document.querySelector('#editorText') }; this.commands = this.commandDefinitions(); }
    commandDefinitions() { return {
      help: ['help [command]', 'Show all commands or detailed usage for one command. Example: help git'], pwd: ['pwd', 'Print the current virtual workspace path.'], ls: ['ls [path]', 'List workspace files. Example: ls ~/projects'], cd: ['cd [path]', 'Change workspace directory. Example: cd ..'], mkdir: ['mkdir [-p] <path>', 'Create a directory. Example: mkdir -p projects/demo'], touch: ['touch <file>', 'Create an empty file. Example: touch notes.txt'], cat: ['cat <file>', 'Print a text file. Example: cat README.md'], write: ['write <file> <content>', 'Write text to a file. Example: write todo.txt "ship Omni"'], rm: ['rm [-r] <path>', 'Remove a file or recursive directory. Example: rm -r old-project'], cp: ['cp <source> <destination>', 'Copy a file. Example: cp todo.txt todo.bak'], mv: ['mv <source> <destination>', 'Move or rename a file/directory. Example: mv draft.md README.md'], tree: ['tree [path]', 'Display a directory tree. Example: tree .'], edit: ['edit <file>', 'Open the built-in text editor. Example: edit notes.txt'], upload: ['upload', 'Import a local text file into the current directory.'], download: ['download <file>', 'Download a virtual workspace file. Example: download notes.txt'], 'fs-access': ['fs-access', 'Choose a local directory with the File System Access API (supported browsers only).'], git: ['git <clone|log|status|repos> ...', 'Browse/import public GitHub repositories. Example: git clone owner/repo'], python3: ['python3 <code>', 'Run persistent Python with Pyodide. Example: python3 "for i in range(3): print(i)"'], pkg: ['pkg <search|install|list> [name]', 'Manage the explicit browser package simulation. Example: pkg install git'], ai: ['ai <help|explain|code|summarize|config> <prompt>', 'Use local assistance or a configured provider endpoint. Example: ai explain "map x to x * 2"'], alias: ['alias [name=command]', 'List or define an alias. Example: alias c=clear'], theme: ['theme [name]', `Set a theme. Example: theme ${THEMES[0]}`], clear: ['clear', 'Clear this session output.'], echo: ['echo <text>', 'Print text. Example: echo hello'], about: ['about', 'Show profile information.'], skills: ['skills', 'Show profile skills.'], projects: ['projects', 'Show projects.'], contact: ['contact', 'Show contact information.'], resume: ['resume', 'Show resume availability.'], socials: ['socials', 'Show social links.'], whoami: ['whoami', 'Show workspace identity.'] }; }
    async boot() { try { const state = await this.storage.load(); if (state) { this.fs = new VirtualFileSystem(state.fs); this.aliases = { ...this.aliases, ...state.aliases }; this.packages = new Set(state.packages || []); this.gitRepos = state.gitRepos || {}; this.aiEndpoint = state.aiEndpoint || ''; this.applyTheme(state.theme || ''); } } catch { /* Persistence is optional in restricted browsing modes. */ } this.newTab('main'); this.print(`${APP} browser workspace ready.`, 'sys'); this.print("Type 'help' for command help. Data is stored locally in IndexedDB.", 'warn'); }
    async persist() { try { await this.storage.save({ fs: this.fs.snapshot(), aliases: this.aliases, theme: this.theme, packages: [...this.packages], gitRepos: this.gitRepos, aiEndpoint: this.aiEndpoint }); } catch { this.print('Storage unavailable: changes will only last for this session.', 'warn'); } }
    newTab(name = 'bash') { const id = `T${Date.now()}_${this.tabs.length}`; const tab = { id, name, cwd: HOME, history: [], hIdx: -1 }; this.tabs.push(tab); const button = document.createElement('button'); button.type = 'button'; button.className = 'tab'; button.id = `btn${id}`; button.textContent = name; button.addEventListener('click', () => this.switch(id)); this.elements.tabs.append(button); const pane = document.createElement('section'); pane.className = 'pane'; pane.id = id; pane.setAttribute('aria-label', `${name} terminal output`); this.elements.terminals.append(pane); this.switch(id); }
    switch(id) { this.tabs.forEach(tab => { document.getElementById(tab.id).classList.remove('active'); document.getElementById(`btn${tab.id}`).classList.remove('active'); }); this.active = this.tabs.find(tab => tab.id === id); document.getElementById(id).classList.add('active'); document.getElementById(`btn${id}`).classList.add('active'); this.updatePrompt(); this.elements.input.focus({ preventScroll: true }); }
    updatePrompt() { this.elements.prompt.textContent = `${this.active.cwd.replace(HOME, '~')} ❯`; }
    print(message = '', kind = '') { const line = document.createElement('div'); line.className = `ln ${kind}`; line.textContent = message; const pane = document.getElementById(this.active.id); pane.append(line); pane.scrollTop = pane.scrollHeight; }
    clear() { document.getElementById(this.active.id).replaceChildren(); }
    usage(command) { const item = this.commands[command]; if (!item) throw new Error(`help: no help topic for '${command}'`); this.print(`${command} — ${item[1]}\nUsage: ${item[0]}`, 'ok'); }
    async execute(raw) { const input = raw.trim(); if (!input) return; const tab = this.active; if (tab.history[0] !== input) tab.history.unshift(input); tab.hIdx = -1; this.print(`${this.elements.prompt.textContent} ${input}`, 'muted'); let [command, ...args] = tokenize(input); command = this.aliases[command] || command; try { await this.run(command, args); } catch (error) { this.print(error.message || 'Command failed.', 'err'); } }
    path(value) { return this.fs.resolve(value, this.active.cwd); } requirePath(label, values) { if (!values[0]) throw new Error(`Usage: ${this.commands[label][0]}`); return this.path(values[0]); }
    async run(command, args) {
      if (command === 'help') { if (args[0]) return this.usage(args[0]); this.print(Object.keys(this.commands).sort().map(name => `${name.padEnd(10)} ${this.commands[name][1]}`).join('\n')); this.print("For details: help <command>. Example: help git", 'warn'); return; }
      if (!this.commands[command] && !['coffee', 'fortune', 'matrix', 'hack', 'sudo'].includes(command)) { const names = Object.keys(this.commands); const suggestion = names.sort((a,b) => distance(command, a) - distance(command, b))[0]; throw new Error(`${APP}: command '${command}' not found.${suggestion && distance(command, suggestion) <= 3 ? ` Did you mean '${suggestion}'?` : " Type 'help' for commands."}`); }
      if (command === 'pwd') return this.print(this.active.cwd); if (command === 'clear') return this.clear(); if (command === 'echo') return this.print(args.join(' '));
      if (command === 'ls') { const target = this.path(args[0] || '.'); return this.print(this.fs.list(target).map(name => this.fs.isDir(this.fs.resolve(name, target)) ? `${name}/` : name).join('  ') || 'Directory empty.', 'ok'); }
      if (command === 'cd') { const target = this.path(args[0] || '~'); if (!this.fs.isDir(target)) throw new Error(`cd: ${args[0] || '~'}: No such directory`); this.active.cwd = target; return this.updatePrompt(); }
      if (command === 'mkdir') { const parents = args[0] === '-p'; const target = this.requirePath('mkdir', parents ? args.slice(1) : args); this.fs.mkdir(target, parents); await this.persist(); return this.print(`created directory '${target}'`, 'ok'); }
      if (command === 'touch') { this.fs.touch(this.requirePath('touch', args)); await this.persist(); return this.print(`touched '${args[0]}'`, 'ok'); }
      if (command === 'cat') return this.print(this.fs.read(this.requirePath('cat', args)));
      if (command === 'write') { if (args.length < 2) throw new Error(`Usage: ${this.commands.write[0]}`); this.fs.write(this.path(args[0]), args.slice(1).join(' ')); await this.persist(); return this.print(`saved '${args[0]}'`, 'ok'); }
      if (command === 'rm') { const recursive = ['-r', '-rf', '-fr'].includes(args[0]); const target = this.requirePath('rm', recursive ? args.slice(1) : args); this.fs.remove(target, recursive); if (this.active.cwd === target || this.active.cwd.startsWith(`${target}/`)) { this.active.cwd = HOME; this.updatePrompt(); } await this.persist(); return this.print(`removed '${target}'`, 'ok'); }
      if (command === 'cp') { if (args.length !== 2) throw new Error(`Usage: ${this.commands.cp[0]}`); const output = this.fs.copy(this.path(args[0]), this.path(args[1])); await this.persist(); return this.print(`copied to '${output}'`, 'ok'); }
      if (command === 'mv') { if (args.length !== 2) throw new Error(`Usage: ${this.commands.mv[0]}`); const output = this.fs.move(this.path(args[0]), this.path(args[1])); await this.persist(); return this.print(`moved to '${output}'`, 'ok'); }
      if (command === 'tree') { const target = this.path(args[0] || '.'); if (!this.fs.isDir(target)) throw new Error(`tree: ${args[0]}: Not a directory`); return this.print(`${target}/\n${this.fs.tree(target).join('\n') || '└── (empty)'}`, 'ok'); }
      if (command === 'edit') return this.openEditor(this.requirePath('edit', args)); if (command === 'upload') return this.upload(); if (command === 'download') return this.download(this.requirePath('download', args)); if (command === 'fs-access') return this.fileSystemAccess();
      if (command === 'alias') { if (!args.length) return this.print(Object.entries(this.aliases).map(([key, value]) => `${key}='${value}'`).join('\n')); const [key, value] = args.join(' ').split('='); if (!key || !value || !/^[\w-]+$/.test(key)) throw new Error(`Usage: ${this.commands.alias[0]}`); this.aliases[key] = value.trim(); await this.persist(); return this.print(`alias ${key}='${this.aliases[key]}'`, 'ok'); }
      if (command === 'theme') { if (!args.length) return this.print(`Current: ${this.theme || 'default'}\nAvailable: default, ${THEMES.join(', ')}`); const selected = args[0] === 'default' ? '' : args[0]; if (selected && !THEMES.includes(selected)) throw new Error(`theme: '${args[0]}' is not available`); this.applyTheme(selected); await this.persist(); return this.print(`Theme switched to ${selected || 'default'}.`, 'ok'); }
      if (command === 'python3') return this.python(args); if (command === 'git') return this.git(args); if (command === 'pkg') return this.pkg(args); if (command === 'ai') return this.ai(args);
      if (Object.hasOwn(PORTFOLIO, command)) return this.print(Array.isArray(PORTFOLIO[command]) ? PORTFOLIO[command].map((item, index) => `${index + 1}. ${item}`).join('\n') : PORTFOLIO[command]); if (command === 'whoami') return this.print(`${PORTFOLIO.name} | ${PORTFOLIO.role}`, 'ok');
      if (command === 'coffee') return this.print('☕ Brewing focus... done. Ship something thoughtful.', 'warn'); if (command === 'fortune') return this.print('“The best interface is the one that lets people finish their work.”'); if (command === 'matrix') return Array.from({ length: 8 }, () => this.print(Math.random().toString(2).slice(2, 42), 'ok')); if (command === 'hack' && args.join(' ') === 'nasa') return this.print('Nice try, commander. This terminal only launches good ideas.', 'warn'); if (command === 'sudo' && args.join(' ') === 'make me a sandwich') return this.print('Okay. 🥪', 'ok');
    }
    async python(args) { if (!args.length || args[0] === 'help') return this.print('Persistent Pyodide session. Usage: python3 <code>\nExamples: python3 "x = 2" | python3 "print(x ** 4)"\nUse standard-library imports supported by Pyodide; browser APIs and native processes are unavailable.', 'ok'); if (!this.py) { this.print('Loading the Pyodide Python runtime…', 'sys'); await this.loadPython(); } const result = await this.py.runPythonAsync(args.join(' ')); if (result !== undefined) this.print(String(result), 'ok'); }
    async loadPython() { if (!window.loadPyodide) await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js'; script.async = true; script.onload = resolve; script.onerror = () => reject(new Error('Python runtime download failed. Connect to the internet, then retry.')); document.head.append(script); }); this.py = await window.loadPyodide({ stdout: text => this.print(text, 'ok'), stderr: text => this.print(text, 'err') }); }
    async git(args) { const [action, value] = args; if (!action || action === 'help') return this.print('GitHub workspace integration (public repositories; API rate limits apply).\nUsage: git clone <owner/repo> | git log <owner/repo> | git repos\nExample: git clone octocat/Hello-World\nThis imports source files into IndexedDB; it is not a native Git clone.', 'ok'); if (action === 'repos') return this.print(Object.entries(this.gitRepos).map(([name, repo]) => `${name}  ${repo.path}`).join('\n') || 'No GitHub repositories imported.'); if (!value || !/^[\w.-]+\/[\w.-]+$/.test(value)) throw new Error('Usage: git clone <owner/repo> or git log <owner/repo>'); if (action === 'log') { const commits = await this.github(`/repos/${value}/commits?per_page=10`); return this.print(commits.map(commit => `${commit.sha.slice(0, 7)} ${commit.commit.message.split('\n')[0]} — ${commit.commit.author.name}`).join('\n'), 'ok'); } if (action !== 'clone') throw new Error(`git: unsupported action '${action}'. Run 'git help'.`); this.print(`Importing ${value} from GitHub…`, 'sys'); const repo = await this.github(`/repos/${value}`); const tree = await this.github(`/repos/${value}/git/trees/${repo.default_branch}?recursive=1`); if (tree.truncated) throw new Error('GitHub returned a truncated tree; this repository is too large for browser import.'); const blobs = tree.tree.filter(item => item.type === 'blob'); if (blobs.length > 200) throw new Error(`Repository has ${blobs.length} files; browser import limit is 200 files. Browse it via GitHub or use a backend worker.`); const base = this.fs.resolve(`projects/${value.replace('/', '-')}`, HOME); this.fs.mkdir(base, true); let imported = 0; for (const item of blobs) { if (item.size > 1024 * 1024) continue; const file = await this.github(`/repos/${value}/contents/${item.path}`); if (file.encoding !== 'base64') continue; const target = this.fs.resolve(item.path, base); this.fs.mkdir(this.fs.parent(target), true); this.fs.write(target, decodeURIComponent(escape(atob(file.content.replace(/\n/g, ''))))); imported++; } this.gitRepos[value] = { path: base, branch: repo.default_branch, importedAt: new Date().toISOString() }; await this.persist(); this.print(`Imported ${imported}/${blobs.length} text files into ${base}. Run: cd ${base}`, 'ok'); }
    async github(path) { const response = await fetch(`https://api.github.com${path}`, { headers: { Accept: 'application/vnd.github+json' } }); if (!response.ok) { if (response.status === 403) throw new Error('GitHub API limit reached or request blocked. Retry later or configure a backend GitHub proxy.'); if (response.status === 404) throw new Error('GitHub repository or resource not found.'); throw new Error(`GitHub API request failed (${response.status}).`); } return response.json(); }
    async pkg(args) { const [action, name] = args; if (!action || action === 'help') return this.print(`Browser package simulation. Packages do not install native binaries.\nUsage: pkg search <term> | pkg install <name> | pkg list\nAvailable: ${Object.keys(PACKAGES).join(', ')}`, 'ok'); if (action === 'list') return this.print([...this.packages].join('\n') || 'No simulated packages installed.'); if (action === 'search') { const matches = Object.entries(PACKAGES).filter(([key, value]) => `${key} ${value}`.includes(name || '')).map(([key, value]) => `${key} — ${value}`); return this.print(matches.join('\n') || 'No package matches.'); } if (action === 'install') { if (!PACKAGES[name]) throw new Error(`pkg: package '${name || ''}' is unavailable. Run 'pkg search <term>'.`); this.packages.add(name); await this.persist(); return this.print(`Installed simulated package: ${name} (${PACKAGES[name]}).`, 'ok'); } throw new Error(`pkg: unsupported action '${action}'. Run 'pkg help'.`); }
    async ai(args) { const action = args.shift(); const prompt = args.join(' ').trim(); if (!action || action === 'help') return this.print('AI command architecture.\nUsage: ai explain <code> | ai summarize <file> | ai code <request> | ai config <https-endpoint>\nWithout a configured endpoint, explain/code use deterministic local guidance. A production provider must be called through a backend that protects credentials.', 'ok'); if (action === 'config') { if (!prompt || !/^https:\/\//.test(prompt)) throw new Error('Usage: ai config <https-endpoint>. Never place provider API keys in this browser app.'); this.aiEndpoint = prompt; await this.persist(); return this.print('AI endpoint saved locally. Requests are sent as JSON { action, prompt }; configure a server-side authenticated proxy.', 'ok'); } if (action === 'summarize') { const content = this.fs.read(this.requirePath('cat', [prompt])); return this.aiRequest(action, `Summarize this file:\n${content}`); } if (!['explain', 'code'].includes(action) || !prompt) throw new Error('Usage: ai explain <text> | ai code <request> | ai summarize <file>'); return this.aiRequest(action, prompt); }
    async aiRequest(action, prompt) { if (this.aiEndpoint) { const response = await fetch(this.aiEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, prompt }) }); if (!response.ok) throw new Error(`AI provider proxy failed (${response.status}).`); const data = await response.json(); return this.print(data.output || data.message || JSON.stringify(data), 'ok'); } if (action === 'explain') return this.print(`Local AI guidance: inspect inputs, outputs, side effects, and failure cases for:\n${prompt}\nConfigure a provider proxy with 'ai config <https-endpoint>' for model-generated analysis.`, 'ok'); if (action === 'code') return this.print(`Local AI guidance: define acceptance criteria, choose a small interface, add error handling, then test the request:\n${prompt}\nConfigure a provider proxy for generated code.`, 'ok'); const words = prompt.replace(/^Summarize this file:\n/, '').trim().split(/\s+/); return this.print(`Local summary (${words.length} words): ${words.slice(0, 45).join(' ')}${words.length > 45 ? '…' : ''}`, 'ok'); }
    openEditor(path) { if (this.fs.isDir(path)) throw new Error(`edit: ${path}: Is a directory`); if (!this.fs.exists(path)) this.fs.touch(path); this.elements.editorPath.value = path; this.elements.editorText.value = this.fs.read(path); this.elements.editor.showModal(); this.elements.editorText.focus(); }
    async saveEditor() { const path = this.elements.editorPath.value; this.fs.write(path, this.elements.editorText.value); await this.persist(); this.elements.editor.close(); this.print(`saved '${path}'`, 'ok'); }
    upload() { const picker = document.createElement('input'); picker.type = 'file'; picker.accept = 'text/*,.md,.js,.json,.py,.html,.css'; picker.addEventListener('change', async () => { const file = picker.files?.[0]; if (!file) return; const path = this.path(file.name); this.fs.write(path, await file.text()); await this.persist(); this.print(`uploaded '${file.name}' (${file.size} bytes)`, 'ok'); }); picker.click(); }
    download(path) { const data = this.fs.read(path); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([data], { type: 'text/plain;charset=utf-8' })); anchor.download = path.split('/').pop(); anchor.click(); URL.revokeObjectURL(anchor.href); this.print(`download started for '${anchor.download}'`, 'ok'); }
    async fileSystemAccess() { if (!window.showDirectoryPicker) throw new Error('File System Access API is unavailable in this browser. Use upload/download instead.'); const directory = await window.showDirectoryPicker(); let count = 0; for await (const [name, handle] of directory.entries()) { if (handle.kind !== 'file') continue; const file = await handle.getFile(); this.fs.write(this.path(name), await file.text()); count++; } await this.persist(); this.print(`Imported ${count} top-level files from ${directory.name}. Browser permissions are session-scoped.`, 'ok'); }
    applyTheme(theme) { this.theme = theme; document.documentElement.dataset.theme = theme; document.querySelector('meta[name="theme-color"]').content = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(); }
    complete() { const value = this.elements.input.value; const tokens = tokenize(value); if (value.endsWith(' ')) return; let candidate = Object.keys(this.commands).concat(Object.keys(this.aliases)); if (tokens.length > 1) { try { candidate = this.fs.list(this.active.cwd); } catch { candidate = []; } } const needle = tokens.at(-1) || ''; const matches = candidate.filter(item => item.startsWith(needle)); if (matches.length === 1) { this.insert(matches[0].slice(needle.length)); this.elements.suggestions.textContent = ''; } else this.elements.suggestions.textContent = matches.length ? `Suggestions: ${matches.join('  ')}` : 'No matching command or file.'; }
    insert(text) { const input = this.elements.input; input.setRangeText(text, input.selectionStart ?? input.value.length, input.selectionEnd ?? input.value.length, 'end'); input.focus({ preventScroll: true }); }
    history(direction) { const tab = this.active; if (direction < 0 && tab.history.length > tab.hIdx + 1) tab.hIdx++; else if (direction > 0 && tab.hIdx >= 0) tab.hIdx--; this.elements.input.value = tab.hIdx >= 0 ? tab.history[tab.hIdx] : ''; }
  }

  const terminal = new Terminal();
  document.querySelector('#newTab').addEventListener('click', () => terminal.newTab());
  document.querySelector('#editorSave').addEventListener('click', () => terminal.saveEditor());
  document.querySelector('#editorCancel').addEventListener('click', () => terminal.elements.editor.close());
  document.querySelector('#keybar').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.insert) terminal.insert(button.dataset.insert); const key = button.dataset.key; if (key === 'ArrowUp') terminal.history(-1); if (key === 'ArrowDown') terminal.history(1); if (key === 'Tab') terminal.complete(); if (key === 'Escape') terminal.elements.input.value = ''; if (key === 'CtrlC') { terminal.elements.input.value = ''; terminal.print('^C', 'err'); } terminal.elements.input.focus({ preventScroll: true }); });
  terminal.elements.input.addEventListener('keydown', async event => { if (event.key === 'Enter') { event.preventDefault(); const value = event.target.value; event.target.value = ''; terminal.elements.suggestions.textContent = ''; await terminal.execute(value); } else if (event.key === 'ArrowUp') { event.preventDefault(); terminal.history(-1); } else if (event.key === 'ArrowDown') { event.preventDefault(); terminal.history(1); } else if (event.key === 'Tab') { event.preventDefault(); terminal.complete(); } else if (event.key === 'Escape') { event.preventDefault(); terminal.elements.input.value = ''; terminal.elements.suggestions.textContent = ''; } else if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); terminal.clear(); } });
  terminal.elements.input.addEventListener('input', () => { terminal.elements.suggestions.textContent = ''; });
  if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('sw.js', { scope: './' }).catch(error => console.warn('Service worker registration failed:', error)));
  terminal.boot();
})();
